# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdrJfxuQPYpCh7KygDwWxDJUHVxb7tDk
"""

import statistics
data=[1,2,3,4,5,6,7]
#mean
mean=statistics.mean(data)
print("mean:",mean)
#median
median=statistics.median(data)
print("median:",median)
#mode
mode=statistics.mode(data)
#variance
variance=statistics.variance(data)
print("variance:",variance)
#standard deviation
std_deviation=statistics.stdev(data)
print("standard deviation:",std_deviation)

